name: Go

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 14 * * *'    

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TELEGRAM_CHESAPEAKE_CHAT_ID: ${{ secrets.TELEGRAM_CHESAPEAKE_CHAT_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        # run: go get .
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Print env
        run: env
      - name: Test with the Go CLI
        run: go run main.go