name: Go

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 14 * * *'    

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TELEGRAM_CHESAPEAKE_CHAT_ID: ${{ secrets.TELEGRAM_CHESAPEAKE_CHAT_ID }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
      - name: Install dependencies
        # run: go get .
        run: go mod tidy
      - name: Build
        run: go build -v ./...
      - name: Print env
        run: env
      - name: Run the go program
        run: ./lunch_menu
        # commit any changes to the repo
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update of lunch menu" || echo "No changes to commit"
          git push origin HEAD:main